In [1]:
import glob
import numpy as np
import pandas as pd

from pathlib import Path

csv_enums = glob.glob("./dataset/*")

column_translation = {
    "지점": "Station",
    "일시": "Date/Time",
    "기온(°C)": "Temperature (°C)",
    "1분 강수량(mm)": "1-minute Precipitation (mm)",
    "강수유무(유무)": "Precipitation Presence (Presence/Absence)",
    "풍향(deg)": "Wind Direction (deg)",
    "풍속(m/s)": "Wind Speed (m/s)",
    "현지기압(hPa)": "Local Pressure (hPa)",
    "해면기압(hPa)": "Sea-level Pressure (hPa)",
    "습도(%)": "Humidity (%)",
    "일사(MJ/m^2)": "Solar Radiation (MJ/m^2)",
    "일조(Sec)": "Sunshine Duration (Sec)",
}

def detect_encoding(file_path):
    """
    Try common Korean encodings.

    CP949 is commonly used for Korean meteorological CSV files.
    """
    file_path = Path(file_path)

    encodings = [
        "utf-8-sig",
        "utf-8",
        "cp949",
        "euc-kr",
    ]

    for encoding in encodings:
        try:
            with open(file_path, "r", encoding=encoding) as f:
                f.read(10000)

            return encoding

        except UnicodeDecodeError:
            continue

    raise UnicodeDecodeError(
        "unknown",
        b"",
        0,
        1,
        f"Could not determine encoding for {file_path}"
    )

# Load and Translate
monthly_data = dict()
for csv_enum in csv_enums:
    # Find Proper encoding to load korean
    encoding = detect_encoding(csv_enum)

    # Load CSV
    loaded_df = pd.read_csv(
        csv_enum, encoding=encoding, dtype=str, keep_default_na=False
    )

    # Translate
    translated_df = loaded_df.rename(columns=column_translation)
    
    key_month_name = pd.to_datetime(translated_df["Date/Time"]).dt.month_name()[0]

    # Store and sort based on months
    monthly_data[key_month_name] = translated_df

In [2]:
print(monthly_data.keys())
print(monthly_data['April'].keys())

dict_keys(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August'])
Index(['Station', 'Date/Time', 'Temperature (°C)',
       '1-minute Precipitation (mm)',
       'Precipitation Presence (Presence/Absence)', 'Wind Direction (deg)',
       'Wind Speed (m/s)', 'Local Pressure (hPa)', 'Sea-level Pressure (hPa)',
       'Humidity (%)', 'Solar Radiation (MJ/m^2)', 'Sunshine Duration (Sec)'],
      dtype='object')

In [3]:
monthly_data['April']['Solar Radiation (MJ/m^2)']

0
1
2
3
4
        ..
43194
43195
43196
43197
43198
Name: Solar Radiation (MJ/m^2), Length: 43199, dtype: object

In [4]:
monthly_data['April']

,Station,Date/Time,Temperature (°C),1-minute Precipitation (mm),Precipitation Presence (Presence/Absence),Wind Direction (deg),Wind Speed (m/s),Local Pressure (hPa),Sea-level Pressure (hPa),Humidity (%),Solar Radiation (MJ/m^2),Sunshine Duration (Sec)
0,939,2026-04-01 00:01,10.6,0,0,323.3,.8,1008.2,1014.2,78.3,,
1,939,2026-04-01 00:02,10.6,0,0,301,.7,1008.2,1014.2,78.5,,
2,939,2026-04-01 00:03,10.6,0,0,303.8,.2,1008.3,1014.3,78.9,,
3,939,2026-04-01 00:04,10.5,0,0,306.7,1.7,1008.3,1014.3,79.1,,
4,939,2026-04-01 00:05,10.6,0,0,334.4,2.1,1008.3,1014.3,79,,
...,...,...,...,...,...,...,...,...,...,...,...,...
43194,939,2026-04-30 23:56,11.7,0,10,288.3,.5,1004,1009.9,93.1,,
43195,939,2026-04-30 23:57,11.7,0,10,304.7,1.5,1004,1009.9,93.1,,
43196,939,2026-04-30 23:58,11.7,0,10,294.7,.7,1004,1009.9,93.2,,
43197,939,2026-04-30 23:59,11.7,0,10,287,.3,1004,1009.9,93.2,,
43198,939,2026-05-01 00:00,11.7,0,10,24.7,.1,1004,1009.9,93.1,,

In [5]:
N_STATES = 5
INITIAL_TRAIN_DAYS = 5
TRAIN_INTERVAL_DAYS = 5
HORIZON = 5
N_ITER = 50

In [6]:
from modules.evaluations import calculate_metrics
from modules.model import get_hmm_features, train_hmm, learn_state_scores, evaluate_day
from modules.feature_process import prepare_data, create_features, create_future_label
from modules.logging import setup_logging

from modules.debug import inspect_precipitation
from modules.export import save_evaluation_json

c:\Users\andro\.conda\envs\weather_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
import logging

output_dir, log_file = setup_logging(
    "./results/"
)
logging.info(
    "Starting HMM walk-forward experiment"
)

df = prepare_data(
    monthly_data
)
inspect_precipitation(df)
df = create_features(df)
df = create_future_label(
    df,
    horizon=HORIZON
)

df["_date"] = (
    df["Date/Time"]
    .dt.normalize()
)

dates = sorted(
    df["_date"]
    .drop_duplicates()
)

2026-08-09 18:59:51,574 | INFO | Starting HMM walk-forward experiment

=== PRECIPITATION CHECK ===

1-minute Precipitation (mm)
dtype: float64
NaN: 776
Unique: [0.0, 0.5, 1.0]
Non-zero: 825
Maximum: 1.0
Value counts:
1-minute Precipitation (mm)
0.0    315237
0.5       824
1.0         1
Name: count, dtype: int64

Precipitation Presence (Presence/Absence)
dtype: float64
NaN: 824
Unique: [0.0, 10.0]
Non-zero: 14123
Maximum: 10.0
Value counts:
Precipitation Presence (Presence/Absence)
0.0     301891
10.0     14123
Name: count, dtype: int64

In [8]:
from tqdm import tqdm

n_folds = (
    len(dates) - INITIAL_TRAIN_DAYS
    + TRAIN_INTERVAL_DAYS - 1
) // TRAIN_INTERVAL_DAYS

logging.info(
    f"Total observations: {len(df):,}"
)

logging.info(
    f"Total days: {len(dates)}"
)

logging.info(
    f"Total folds: {n_folds}"
)

logging.info(
    f"N_STATES={N_STATES}, "
    f"INITIAL_TRAIN_DAYS={INITIAL_TRAIN_DAYS}, "
    f"TRAIN_INTERVAL_DAYS={TRAIN_INTERVAL_DAYS}, "
    f"HORIZON={HORIZON}, "
    f"N_ITER={N_ITER}"
)
# ----------------------------------------
# Storage
# ----------------------------------------

all_results = []
metrics = []

previous_hmm = None

# ----------------------------------------
# Walk forward
# ----------------------------------------

train_end = INITIAL_TRAIN_DAYS
fold = 0

with tqdm(
    total=n_folds,
    desc="Walk-forward HMM",
    unit="fold"
) as pbar:
    while train_end < len(dates):
        fold += 1
        train_dates = dates[:train_end]

        eval_dates = dates[
            train_end:
            train_end + 1
        ]

        if not eval_dates:
            break

        # ------------------------------------------------
        # Progress description
        # ------------------------------------------------

        pbar.set_postfix_str(
            f"Train={train_dates[0]:%Y-%m-%d}"
            f"→{train_dates[-1]:%Y-%m-%d} | "
            f"Eval={eval_dates[0]:%Y-%m-%d}"
        )

        logging.info(
            f"Fold {fold}/{n_folds} | "
            f"Train: "
            f"{train_dates[0]:%Y-%m-%d}"
            f"→"
            f"{train_dates[-1]:%Y-%m-%d} | "
            f"Eval: "
            f"{eval_dates[0]:%Y-%m-%d}"
        )

        # ------------------------------------------------
        # Split
        # ------------------------------------------------

        train_df = df[
            df["_date"].isin(train_dates)
        ]

        #print(train_df)

        eval_df = df[
            df["_date"].isin(eval_dates)
        ]

        logging.info(
            f"Training rows: {len(train_df):,} | "
            f"Evaluation rows: {len(eval_df):,}"
        )

        # ------------------------------------------------
        # Train HMM
        # ------------------------------------------------

        hmm, scaler = train_hmm(
            train_df,
            previous_hmm=previous_hmm,
            n_states=N_STATES,
            n_iter=N_ITER,
        )

        logging.info(
            f"HMM trained | "
            f"iterations={hmm.monitor_.iter} | "
            f"converged={hmm.monitor_.converged}"
        )

        # ------------------------------------------------
        # State → rain mapping
        # ------------------------------------------------

        state_scores = learn_state_scores(
            train_df,
            hmm,
            scaler,
        )

        logging.info(
            "State rain scores: "
            + np.array2string(
                state_scores,
                precision=4
            )
        )

        # ------------------------------------------------
        # Evaluate
        # ------------------------------------------------

        result = evaluate_day(
            eval_df,
            hmm,
            scaler,
            state_scores,
        )

        result["Fold"] = fold
        result["Eval_Date"] = eval_dates[0]

        all_results.append(result)

        # ------------------------------------------------
        # Metrics
        # ------------------------------------------------

        fold_metrics = calculate_metrics(
            result
        )

        eval_start = eval_df["Date/Time"].min()
        eval_end = eval_df["Date/Time"].max()

        fold_metrics.update({
            "Fold": fold,
            "Eval_Date": eval_dates[0],
            "Train_Start": train_dates[0],
            "Train_End": train_dates[-1],
            "N_Train_Rows": len(train_df),
            "N_Eval_Rows": len(result),
        })

        metrics.append(
            fold_metrics
        )

        # ------------------------------------------------
        # Save metrics immediately
        # ------------------------------------------------

        metrics_df = pd.DataFrame(
            metrics
        )

        print(fold)
        save_evaluation_json(
            result=result,
            fold=fold,
            train_start=train_dates[0],
            train_end=train_dates[-1],
            eval_start=eval_start,
            eval_end=eval_end,
            metrics=metrics_df,
            output_dir="evaluation_logs",
        )

        metrics_df.to_csv(
            output_dir /
            "fold_metrics.csv",
            index=False
        )

        # ------------------------------------------------
        # Save current evaluation
        # ------------------------------------------------

        result.to_csv(
            output_dir /
            f"fold_{fold:03d}_evaluation.csv",
            index=False
        )

        # ------------------------------------------------
        # Log metrics
        # ------------------------------------------------

        logging.info(
            f"Fold {fold} metrics | "
            f"Brier={fold_metrics['Brier']:.4f} | "
            f"ROC-AUC={fold_metrics['ROC_AUC']:.4f} | "
            f"PR-AUC={fold_metrics['PR_AUC']:.4f} | "
            f"F1={fold_metrics['F1']:.4f}"
        )

        # ------------------------------------------------
        # Keep model
        # ------------------------------------------------

        previous_hmm = hmm

        # ------------------------------------------------
        # Advance by TRAIN_INTERVAL_DAYS
        # ------------------------------------------------

        #print(type(TRAIN_INTERVAL_DAYS), TRAIN_INTERVAL_DAYS)
        train_end += TRAIN_INTERVAL_DAYS

        pbar.update(1)

    # ========================================================
    # COMBINE RESULTS
    # ========================================================

    results_df = (
        pd.concat(
            all_results,
            ignore_index=True
        )
        if all_results
        else pd.DataFrame()
    )

    metrics_df = pd.DataFrame(
        metrics
    )

    results_df.to_csv(
        output_dir /
        "all_evaluation_results.csv",
        index=False
    )

    metrics_df.to_csv(
        output_dir /
        "fold_metrics.csv",
        index=False
    )

    if len(results_df) > 0:

        overall = calculate_metrics(
            results_df
        )

        overall_df = pd.DataFrame(
            [overall]
        )

        overall_df.to_csv(
            output_dir /
            "overall_metrics.csv",
            index=False
        )

        logging.info(
            f"Overall metrics | "
            f"Brier={overall['Brier']:.4f} | "
            f"ROC-AUC={overall['ROC_AUC']:.4f} | "
            f"PR-AUC={overall['PR_AUC']:.4f} | "
            f"F1={overall['F1']:.4f}"
        )

    logging.info(
        f"Experiment complete. "
        f"Results saved to: {output_dir}"
    )

2026-08-09 18:59:53,143 | INFO | Total observations: 316,838
2026-08-09 18:59:53,144 | INFO | Total days: 221
2026-08-09 18:59:53,144 | INFO | Total folds: 44
2026-08-09 18:59:53,145 | INFO | N_STATES=5, INITIAL_TRAIN_DAYS=5, TRAIN_INTERVAL_DAYS=5, HORIZON=5, N_ITER=50
Walk-forward HMM:   0%|          | 0/44 [00:00<?, ?fold/s, Train=2026-01-01→2026-01-05 | Eval=2026-01-06]2026-08-09 18:59:53,148 | INFO | Fold 1/44 | Train: 2026-01-01→2026-01-05 | Eval: 2026-01-06
2026-08-09 18:59:53,153 | INFO | Training rows: 7,198 | Evaluation rows: 1,440
2026-08-09 18:59:55,265 | INFO | HMM trained | iterations=38 | converged=True
2026-08-09 18:59:55,277 | INFO | State rain scores: [0. 0. 0. 0. 0.]
2026-08-09 18:59:55,510 | INFO | Fold 1 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000

1

Walk-forward HMM:   2%|▏         | 1/44 [00:02<01:41,  2.36s/fold, Train=2026-01-01→2026-01-10 | Eval=2026-01-11]2026-08-09 18:59:55,512 | INFO | Fold 2/44 | Train: 2026-01-01→2026-01-10 | Eval: 2026-01-11
2026-08-09 18:59:55,518 | INFO | Training rows: 14,398 | Evaluation rows: 1,440
2026-08-09 18:59:56,335 | WARNING | Model is not converging.  Current: 94728.33821164069 is not greater than 94728.3415192677. Delta is -0.0033076270192395896
2026-08-09 18:59:56,336 | INFO | HMM trained | iterations=24 | converged=True
2026-08-09 18:59:56,350 | INFO | State rain scores: [0. 0. 0. 0. 0.]

2

2026-08-09 18:59:56,585 | INFO | Fold 2 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   5%|▍         | 2/44 [00:03<01:07,  1.61s/fold, Train=2026-01-01→2026-01-15 | Eval=2026-01-16]2026-08-09 18:59:56,587 | INFO | Fold 3/44 | Train: 2026-01-01→2026-01-15 | Eval: 2026-01-16
2026-08-09 18:59:56,594 | INFO | Training rows: 21,597 | Evaluation rows: 1,440
2026-08-09 18:59:57,832 | INFO | HMM trained | iterations=24 | converged=True
2026-08-09 18:59:57,854 | INFO | State rain scores: [0.0000e+00 0.0000e+00 5.5443e-04 0.0000e+00 6.7733e-01]

3

2026-08-09 18:59:58,088 | INFO | Fold 3 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   7%|▋         | 3/44 [00:04<01:03,  1.56s/fold, Train=2026-01-01→2026-01-20 | Eval=2026-01-21]2026-08-09 18:59:58,090 | INFO | Fold 4/44 | Train: 2026-01-01→2026-01-20 | Eval: 2026-01-21
2026-08-09 18:59:58,098 | INFO | Training rows: 28,797 | Evaluation rows: 1,440
2026-08-09 19:00:00,011 | INFO | HMM trained | iterations=32 | converged=True
2026-08-09 19:00:00,044 | INFO | State rain scores: [0.0000e+00 0.0000e+00 4.5196e-04 0.0000e+00 6.7733e-01]

4

2026-08-09 19:00:00,284 | INFO | Fold 4 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:   9%|▉         | 4/44 [00:07<01:12,  1.81s/fold, Train=2026-01-01→2026-01-25 | Eval=2026-01-26]2026-08-09 19:00:00,286 | INFO | Fold 5/44 | Train: 2026-01-01→2026-01-25 | Eval: 2026-01-26
2026-08-09 19:00:00,295 | INFO | Training rows: 35,996 | Evaluation rows: 1,440
2026-08-09 19:00:02,912 | INFO | HMM trained | iterations=36 | converged=True
2026-08-09 19:00:02,946 | INFO | State rain scores: [0.0000e+00 0.0000e+00 3.2130e-04 0.0000e+00 6.7733e-01]

5

2026-08-09 19:00:03,225 | INFO | Fold 5 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  11%|█▏        | 5/44 [00:10<01:26,  2.22s/fold, Train=2026-01-01→2026-01-30 | Eval=2026-01-31]2026-08-09 19:00:03,227 | INFO | Fold 6/44 | Train: 2026-01-01→2026-01-30 | Eval: 2026-01-31
2026-08-09 19:00:03,236 | INFO | Training rows: 43,196 | Evaluation rows: 1,440
2026-08-09 19:00:07,639 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:00:07,687 | INFO | State rain scores: [0.     0.     0.     0.0034 0.6773]

6

2026-08-09 19:00:07,925 | INFO | Fold 6 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  14%|█▎        | 6/44 [00:14<01:56,  3.06s/fold, Train=2026-01-01→2026-02-04 | Eval=2026-02-05]2026-08-09 19:00:07,927 | INFO | Fold 7/44 | Train: 2026-01-01→2026-02-04 | Eval: 2026-02-05
2026-08-09 19:00:07,936 | INFO | Training rows: 50,395 | Evaluation rows: 1,439
2026-08-09 19:00:10,986 | INFO | HMM trained | iterations=30 | converged=True
2026-08-09 19:00:11,043 | INFO | State rain scores: [0.     0.     0.     0.0031 0.6773]

7

2026-08-09 19:00:11,294 | INFO | Fold 7 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  16%|█▌        | 7/44 [00:18<01:57,  3.16s/fold, Train=2026-01-01→2026-02-09 | Eval=2026-02-10]2026-08-09 19:00:11,296 | INFO | Fold 8/44 | Train: 2026-01-01→2026-02-09 | Eval: 2026-02-10
2026-08-09 19:00:11,306 | INFO | Training rows: 57,594 | Evaluation rows: 1,440
2026-08-09 19:00:17,347 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:00:17,402 | INFO | State rain scores: [5.6634e-04 0.0000e+00 0.0000e+00 3.3293e-03 6.1190e-01]

8

2026-08-09 19:00:17,650 | INFO | Fold 8 metrics | Brier=0.0280 | ROC-AUC=0.9591 | PR-AUC=0.6417 | F1=0.7722
Walk-forward HMM:  18%|█▊        | 8/44 [00:24<02:30,  4.18s/fold, Train=2026-01-01→2026-02-14 | Eval=2026-02-15]2026-08-09 19:00:17,652 | INFO | Fold 9/44 | Train: 2026-01-01→2026-02-14 | Eval: 2026-02-15
2026-08-09 19:00:17,662 | INFO | Training rows: 64,794 | Evaluation rows: 1,440
2026-08-09 19:00:24,127 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:00:24,192 | INFO | State rain scores: [4.0876e-04 4.6751e-04 1.3631e-04 3.5777e-03 6.0748e-01]

9

2026-08-09 19:00:24,428 | INFO | Fold 9 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  20%|██        | 9/44 [00:31<02:54,  4.99s/fold, Train=2026-01-01→2026-02-19 | Eval=2026-02-20]2026-08-09 19:00:24,430 | INFO | Fold 10/44 | Train: 2026-01-01→2026-02-19 | Eval: 2026-02-20
2026-08-09 19:00:24,440 | INFO | Training rows: 71,992 | Evaluation rows: 1,440
2026-08-09 19:00:31,606 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:00:31,680 | INFO | State rain scores: [5.1722e-04 3.7576e-04 8.6908e-05 3.0499e-03 5.3313e-01]

10

2026-08-09 19:00:31,919 | INFO | Fold 10 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  23%|██▎       | 10/44 [00:38<03:15,  5.76s/fold, Train=2026-01-01→2026-02-24 | Eval=2026-02-25]2026-08-09 19:00:31,921 | INFO | Fold 11/44 | Train: 2026-01-01→2026-02-24 | Eval: 2026-02-25
2026-08-09 19:00:31,934 | INFO | Training rows: 79,192 | Evaluation rows: 1,439
2026-08-09 19:00:40,171 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:00:40,265 | INFO | State rain scores: [7.6800e-04 4.2887e-04 2.0731e-04 0.0000e+00 8.4735e-01]

11

2026-08-09 19:00:40,504 | INFO | Fold 11 metrics | Brier=0.0046 | ROC-AUC=0.9660 | PR-AUC=0.7707 | F1=0.8732
Walk-forward HMM:  25%|██▌       | 11/44 [00:47<03:38,  6.63s/fold, Train=2026-01-01→2026-03-01 | Eval=2026-03-02]2026-08-09 19:00:40,505 | INFO | Fold 12/44 | Train: 2026-01-01→2026-03-01 | Eval: 2026-03-02
2026-08-09 19:00:40,519 | INFO | Training rows: 86,390 | Evaluation rows: 1,440
2026-08-09 19:00:45,389 | INFO | HMM trained | iterations=25 | converged=True
2026-08-09 19:00:45,477 | INFO | State rain scores: [8.0450e-04 2.7664e-04 1.1812e-04 0.0000e+00 8.7758e-01]

12

2026-08-09 19:00:45,715 | INFO | Fold 12 metrics | Brier=0.0293 | ROC-AUC=0.9448 | PR-AUC=0.9523 | F1=0.9738
Walk-forward HMM:  27%|██▋       | 12/44 [00:52<03:18,  6.20s/fold, Train=2026-01-01→2026-03-06 | Eval=2026-03-07]2026-08-09 19:00:45,717 | INFO | Fold 13/44 | Train: 2026-01-01→2026-03-06 | Eval: 2026-03-07
2026-08-09 19:00:45,730 | INFO | Training rows: 93,590 | Evaluation rows: 1,440
2026-08-09 19:00:50,590 | INFO | HMM trained | iterations=23 | converged=True
2026-08-09 19:00:50,685 | INFO | State rain scores: [1.4087e-03 2.6843e-04 0.0000e+00 0.0000e+00 8.7811e-01]

13

2026-08-09 19:00:50,921 | INFO | Fold 13 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  30%|██▉       | 13/44 [00:57<03:02,  5.90s/fold, Train=2026-01-01→2026-03-11 | Eval=2026-03-12]2026-08-09 19:00:50,923 | INFO | Fold 14/44 | Train: 2026-01-01→2026-03-11 | Eval: 2026-03-12
2026-08-09 19:00:50,936 | INFO | Training rows: 100,789 | Evaluation rows: 1,440
2026-08-09 19:01:01,180 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:01:01,280 | INFO | State rain scores: [1.2574e-03 2.4162e-04 0.0000e+00 0.0000e+00 8.7811e-01]

14

2026-08-09 19:01:01,517 | INFO | Fold 14 metrics | Brier=0.0186 | ROC-AUC=0.9637 | PR-AUC=0.5974 | F1=0.7376
Walk-forward HMM:  32%|███▏      | 14/44 [01:08<03:39,  7.32s/fold, Train=2026-01-01→2026-03-16 | Eval=2026-03-17]2026-08-09 19:01:01,518 | INFO | Fold 15/44 | Train: 2026-01-01→2026-03-16 | Eval: 2026-03-17
2026-08-09 19:01:01,533 | INFO | Training rows: 107,989 | Evaluation rows: 1,440
2026-08-09 19:01:12,420 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:01:12,529 | INFO | State rain scores: [1.5052e-03 2.1606e-04 0.0000e+00 6.1150e-04 8.4903e-01]

15

2026-08-09 19:01:12,765 | INFO | Fold 15 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  34%|███▍      | 15/44 [01:19<04:06,  8.50s/fold, Train=2026-01-01→2026-03-21 | Eval=2026-03-22]2026-08-09 19:01:12,767 | INFO | Fold 16/44 | Train: 2026-01-01→2026-03-21 | Eval: 2026-03-22
2026-08-09 19:01:12,785 | INFO | Training rows: 115,188 | Evaluation rows: 1,440
2026-08-09 19:01:24,422 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:01:24,536 | INFO | State rain scores: [1.3438e-03 6.9668e-04 0.0000e+00 5.8281e-04 8.5518e-01]

16

2026-08-09 19:01:24,807 | INFO | Fold 16 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  36%|███▋      | 16/44 [01:31<04:27,  9.57s/fold, Train=2026-01-01→2026-03-26 | Eval=2026-03-27]2026-08-09 19:01:24,809 | INFO | Fold 17/44 | Train: 2026-01-01→2026-03-26 | Eval: 2026-03-27
2026-08-09 19:01:24,825 | INFO | Training rows: 122,388 | Evaluation rows: 1,440
2026-08-09 19:01:37,147 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:01:37,272 | INFO | State rain scores: [1.2898e-03 7.4309e-04 0.0000e+00 1.7778e-03 8.4922e-01]

17

2026-08-09 19:01:37,515 | INFO | Fold 17 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  39%|███▊      | 17/44 [01:44<04:43, 10.51s/fold, Train=2026-01-01→2026-03-31 | Eval=2026-04-01]2026-08-09 19:01:37,517 | INFO | Fold 18/44 | Train: 2026-01-01→2026-03-31 | Eval: 2026-04-01
2026-08-09 19:01:37,535 | INFO | Training rows: 129,588 | Evaluation rows: 1,439
2026-08-09 19:01:49,312 | INFO | HMM trained | iterations=45 | converged=True
2026-08-09 19:01:49,437 | INFO | State rain scores: [1.7469e-03 7.4744e-04 0.0000e+00 2.7778e-03 8.5113e-01]

18

2026-08-09 19:01:49,673 | INFO | Fold 18 metrics | Brier=0.0086 | ROC-AUC=0.9472 | PR-AUC=0.6144 | F1=0.7708
Walk-forward HMM:  41%|████      | 18/44 [01:56<04:46, 11.01s/fold, Train=2026-01-01→2026-04-05 | Eval=2026-04-06]2026-08-09 19:01:49,674 | INFO | Fold 19/44 | Train: 2026-01-01→2026-04-05 | Eval: 2026-04-06
2026-08-09 19:01:49,693 | INFO | Training rows: 136,787 | Evaluation rows: 1,440
2026-08-09 19:01:59,788 | INFO | HMM trained | iterations=35 | converged=True
2026-08-09 19:01:59,929 | INFO | State rain scores: [1.7183e-03 7.9135e-04 0.0000e+00 2.7158e-03 8.6288e-01]

19

2026-08-09 19:02:00,175 | INFO | Fold 19 metrics | Brier=0.0235 | ROC-AUC=0.9288 | PR-AUC=0.4473 | F1=0.6316
Walk-forward HMM:  43%|████▎     | 19/44 [02:07<04:31, 10.85s/fold, Train=2026-01-01→2026-04-10 | Eval=2026-04-11]2026-08-09 19:02:00,177 | INFO | Fold 20/44 | Train: 2026-01-01→2026-04-10 | Eval: 2026-04-11
2026-08-09 19:02:00,195 | INFO | Training rows: 143,987 | Evaluation rows: 1,440
2026-08-09 19:02:14,801 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:02:14,941 | INFO | State rain scores: [2.2125e-03 7.5346e-04 0.0000e+00 1.4028e-03 8.5660e-01]

20

2026-08-09 19:02:15,174 | INFO | Fold 20 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  45%|████▌     | 20/44 [02:22<04:50, 12.10s/fold, Train=2026-01-01→2026-04-15 | Eval=2026-04-16]2026-08-09 19:02:15,176 | INFO | Fold 21/44 | Train: 2026-01-01→2026-04-15 | Eval: 2026-04-16
2026-08-09 19:02:15,195 | INFO | Training rows: 151,187 | Evaluation rows: 1,440
2026-08-09 19:02:30,531 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:02:30,691 | INFO | State rain scores: [2.0678e-03 7.7029e-04 1.0692e-04 1.4403e-03 8.5250e-01]

21

2026-08-09 19:02:30,923 | INFO | Fold 21 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  48%|████▊     | 21/44 [02:37<05:03, 13.19s/fold, Train=2026-01-01→2026-04-20 | Eval=2026-04-21]2026-08-09 19:02:30,925 | INFO | Fold 22/44 | Train: 2026-01-01→2026-04-20 | Eval: 2026-04-21
2026-08-09 19:02:30,951 | INFO | Training rows: 158,387 | Evaluation rows: 1,440
2026-08-09 19:02:47,065 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:02:47,233 | INFO | State rain scores: [2.4022e-03 4.8653e-04 0.0000e+00 1.4629e-03 8.4822e-01]

22

2026-08-09 19:02:47,476 | INFO | Fold 22 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  50%|█████     | 22/44 [02:54<05:12, 14.20s/fold, Train=2026-01-01→2026-04-25 | Eval=2026-04-26]2026-08-09 19:02:47,477 | INFO | Fold 23/44 | Train: 2026-01-01→2026-04-25 | Eval: 2026-04-26
2026-08-09 19:02:47,496 | INFO | Training rows: 165,586 | Evaluation rows: 1,440
2026-08-09 19:03:02,608 | INFO | HMM trained | iterations=45 | converged=True
2026-08-09 19:03:02,770 | INFO | State rain scores: [2.5878e-03 4.5941e-04 0.0000e+00 1.5184e-03 8.3272e-01]

23

2026-08-09 19:03:03,005 | INFO | Fold 23 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  52%|█████▏    | 23/44 [03:09<05:06, 14.60s/fold, Train=2026-01-01→2026-04-30 | Eval=2026-05-01]2026-08-09 19:03:03,007 | INFO | Fold 24/44 | Train: 2026-01-01→2026-04-30 | Eval: 2026-05-01
2026-08-09 19:03:03,028 | INFO | Training rows: 172,786 | Evaluation rows: 1,440
2026-08-09 19:03:19,304 | INFO | HMM trained | iterations=48 | converged=True
2026-08-09 19:03:19,444 | INFO | State rain scores: [2.5177e-03 6.2478e-04 0.0000e+00 1.3685e-03 8.3380e-01]

24

2026-08-09 19:03:19,678 | INFO | Fold 24 metrics | Brier=0.0533 | ROC-AUC=0.9179 | PR-AUC=0.7030 | F1=0.8228
Walk-forward HMM:  55%|█████▍    | 24/44 [03:26<05:04, 15.22s/fold, Train=2026-01-01→2026-05-05 | Eval=2026-05-06]2026-08-09 19:03:19,680 | INFO | Fold 25/44 | Train: 2026-01-01→2026-05-05 | Eval: 2026-05-06
2026-08-09 19:03:19,701 | INFO | Training rows: 179,986 | Evaluation rows: 1,440
2026-08-09 19:03:29,956 | INFO | HMM trained | iterations=29 | converged=True
2026-08-09 19:03:30,121 | INFO | State rain scores: [2.6709e-03 6.9777e-04 1.6179e-04 1.3449e-03 8.3326e-01]

25

2026-08-09 19:03:30,355 | INFO | Fold 25 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  57%|█████▋    | 25/44 [03:37<04:23, 13.86s/fold, Train=2026-01-01→2026-05-10 | Eval=2026-05-11]2026-08-09 19:03:30,356 | INFO | Fold 26/44 | Train: 2026-01-01→2026-05-10 | Eval: 2026-05-11
2026-08-09 19:03:30,378 | INFO | Training rows: 187,186 | Evaluation rows: 1,440
2026-08-09 19:03:45,014 | INFO | HMM trained | iterations=40 | converged=True
2026-08-09 19:03:45,182 | INFO | State rain scores: [2.1681e-03 1.6996e-03 1.4449e-04 1.2248e-03 8.3113e-01]

26

2026-08-09 19:03:45,416 | INFO | Fold 26 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  59%|█████▉    | 26/44 [03:52<04:15, 14.22s/fold, Train=2026-01-01→2026-05-15 | Eval=2026-05-16]2026-08-09 19:03:45,417 | INFO | Fold 27/44 | Train: 2026-01-01→2026-05-15 | Eval: 2026-05-16
2026-08-09 19:03:45,440 | INFO | Training rows: 194,385 | Evaluation rows: 1,439
2026-08-09 19:04:04,429 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:04:04,588 | INFO | State rain scores: [2.1236e-03 1.7519e-03 1.3846e-04 1.1986e-03 8.2836e-01]

27

2026-08-09 19:04:04,819 | INFO | Fold 27 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  61%|██████▏   | 27/44 [04:11<04:28, 15.77s/fold, Train=2026-01-01→2026-05-20 | Eval=2026-05-21]2026-08-09 19:04:04,821 | INFO | Fold 28/44 | Train: 2026-01-01→2026-05-20 | Eval: 2026-05-21
2026-08-09 19:04:04,842 | INFO | Training rows: 201,583 | Evaluation rows: 1,440
2026-08-09 19:04:24,590 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:04:24,790 | INFO | State rain scores: [2.2418e-03 1.8496e-03 1.4122e-04 1.2670e-03 8.3623e-01]

28

2026-08-09 19:04:25,056 | INFO | Fold 28 metrics | Brier=0.0511 | ROC-AUC=0.9334 | PR-AUC=0.6703 | F1=0.7978
Walk-forward HMM:  64%|██████▎   | 28/44 [04:31<04:33, 17.11s/fold, Train=2026-01-01→2026-05-25 | Eval=2026-05-26]2026-08-09 19:04:25,058 | INFO | Fold 29/44 | Train: 2026-01-01→2026-05-25 | Eval: 2026-05-26
2026-08-09 19:04:25,080 | INFO | Training rows: 208,783 | Evaluation rows: 1,440
2026-08-09 19:04:46,522 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:04:46,721 | INFO | State rain scores: [2.1814e-03 2.1927e-03 1.2725e-04 1.0221e-03 8.3044e-01]

29

2026-08-09 19:04:46,955 | INFO | Fold 29 metrics | Brier=0.0063 | ROC-AUC=0.9937 | PR-AUC=0.9911 | F1=0.9937
Walk-forward HMM:  66%|██████▌   | 29/44 [04:53<04:38, 18.55s/fold, Train=2026-01-01→2026-05-30 | Eval=2026-05-31]2026-08-09 19:04:46,957 | INFO | Fold 30/44 | Train: 2026-01-01→2026-05-30 | Eval: 2026-05-31
2026-08-09 19:04:46,981 | INFO | Training rows: 215,983 | Evaluation rows: 1,440
2026-08-09 19:05:09,099 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:05:09,308 | INFO | State rain scores: [2.4296e-03 2.8316e-03 6.4329e-04 0.0000e+00 8.3133e-01]

30

2026-08-09 19:05:09,542 | INFO | Fold 30 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  68%|██████▊   | 30/44 [05:16<04:36, 19.76s/fold, Train=2026-01-01→2026-06-04 | Eval=2026-06-05]2026-08-09 19:05:09,544 | INFO | Fold 31/44 | Train: 2026-01-01→2026-06-04 | Eval: 2026-06-05
2026-08-09 19:05:09,569 | INFO | Training rows: 223,183 | Evaluation rows: 1,440
2026-08-09 19:05:29,227 | INFO | HMM trained | iterations=43 | converged=True
2026-08-09 19:05:29,422 | INFO | State rain scores: [2.6982e-03 2.8552e-03 6.6973e-04 2.3102e-03 8.3814e-01]

31

2026-08-09 19:05:29,656 | INFO | Fold 31 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  70%|███████   | 31/44 [05:36<04:18, 19.87s/fold, Train=2026-01-01→2026-06-09 | Eval=2026-06-10]2026-08-09 19:05:29,658 | INFO | Fold 32/44 | Train: 2026-01-01→2026-06-09 | Eval: 2026-06-10
2026-08-09 19:05:29,682 | INFO | Training rows: 230,382 | Evaluation rows: 1,440
2026-08-09 19:05:53,227 | INFO | HMM trained | iterations=50 | converged=True
2026-08-09 19:05:53,447 | INFO | State rain scores: [2.7980e-03 2.9930e-03 6.7401e-04 2.2913e-03 8.3134e-01]

32

2026-08-09 19:05:53,684 | INFO | Fold 32 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  73%|███████▎  | 32/44 [06:00<04:13, 21.11s/fold, Train=2026-01-01→2026-06-14 | Eval=2026-06-15]2026-08-09 19:05:53,685 | INFO | Fold 33/44 | Train: 2026-01-01→2026-06-14 | Eval: 2026-06-15
2026-08-09 19:05:53,713 | INFO | Training rows: 237,582 | Evaluation rows: 1,440
2026-08-09 19:06:12,637 | INFO | HMM trained | iterations=38 | converged=True
2026-08-09 19:06:12,866 | INFO | State rain scores: [2.4171e-03 3.1674e-03 6.9989e-04 2.3729e-03 8.3134e-01]

33

2026-08-09 19:06:13,101 | INFO | Fold 33 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  75%|███████▌  | 33/44 [06:19<03:46, 20.61s/fold, Train=2026-01-01→2026-06-19 | Eval=2026-06-20]2026-08-09 19:06:13,103 | INFO | Fold 34/44 | Train: 2026-01-01→2026-06-19 | Eval: 2026-06-20
2026-08-09 19:06:13,130 | INFO | Training rows: 244,782 | Evaluation rows: 1,439
2026-08-09 19:06:29,175 | WARNING | Model is not converging.  Current: 2128835.617145399 is not greater than 2128835.617274912. Delta is -0.0001295129768550396
2026-08-09 19:06:29,183 | INFO | HMM trained | iterations=32 | converged=True
2026-08-09 19:06:29,440 | INFO | State rain scores: [2.4663e-03 2.9868e-03 7.0429e-04 2.2727e-03 8.2973e-01]
2026-08-09 19:06:29,572 | INFO | Fold 34 metrics | Brier=0.0536 | ROC-AUC=0.6168 | PR-AUC=0.9514 | F1=0.9723
Walk-forward HMM:  77%|███████▋  | 34/44 [06:36<03:13, 19.37s/fold, Train=2026-01-01→2026-06-24 | Eval=2026-06-25]2026-08-09 19:06:29,574 | INFO | Fold 35/44 | Train: 2026-01-01→2026-06-24 | Eval: 2026-06-25
2026-08-09 19:06:29,601 | INFO | Training rows: 251,980 | Evaluation rows: 1,440

34

2026-08-09 19:06:46,633 | INFO | HMM trained | iterations=33 | converged=True
2026-08-09 19:06:46,880 | INFO | State rain scores: [3.3003e-03 2.8993e-03 6.8957e-04 2.2117e-03 8.1900e-01]

35

2026-08-09 19:06:47,113 | INFO | Fold 35 metrics | Brier=0.0156 | ROC-AUC=0.9746 | PR-AUC=0.7616 | F1=0.8651
Walk-forward HMM:  80%|███████▉  | 35/44 [06:53<02:49, 18.82s/fold, Train=2026-01-01→2026-06-29 | Eval=2026-06-30]2026-08-09 19:06:47,115 | INFO | Fold 36/44 | Train: 2026-01-01→2026-06-29 | Eval: 2026-06-30
2026-08-09 19:06:47,145 | INFO | Training rows: 259,179 | Evaluation rows: 1,440
2026-08-09 19:07:03,167 | INFO | HMM trained | iterations=30 | converged=True
2026-08-09 19:07:03,411 | INFO | State rain scores: [3.2465e-03 2.8970e-03 6.7986e-04 2.1148e-03 8.1754e-01]

36

2026-08-09 19:07:03,646 | INFO | Fold 36 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  82%|████████▏ | 36/44 [07:10<02:25, 18.13s/fold, Train=2026-01-01→2026-07-04 | Eval=2026-07-05]2026-08-09 19:07:03,648 | INFO | Fold 37/44 | Train: 2026-01-01→2026-07-04 | Eval: 2026-07-05
2026-08-09 19:07:03,676 | INFO | Training rows: 266,379 | Evaluation rows: 1,439
2026-08-09 19:07:17,945 | INFO | HMM trained | iterations=26 | converged=True
2026-08-09 19:07:18,210 | INFO | State rain scores: [3.3034e-03 3.2396e-03 6.8183e-04 2.0927e-03 8.1755e-01]

37

2026-08-09 19:07:18,448 | INFO | Fold 37 metrics | Brier=0.0447 | ROC-AUC=0.9106 | PR-AUC=0.4484 | F1=0.6175
Walk-forward HMM:  84%|████████▍ | 37/44 [07:25<01:59, 17.13s/fold, Train=2026-01-01→2026-07-09 | Eval=2026-07-10]2026-08-09 19:07:18,450 | INFO | Fold 38/44 | Train: 2026-01-01→2026-07-09 | Eval: 2026-07-10
2026-08-09 19:07:18,478 | INFO | Training rows: 273,578 | Evaluation rows: 1,440
2026-08-09 19:07:31,393 | WARNING | Model is not converging.  Current: 2381231.2843541023 is not greater than 2381231.284963696. Delta is -0.000609593465924263
2026-08-09 19:07:31,402 | INFO | HMM trained | iterations=23 | converged=True
2026-08-09 19:07:31,670 | INFO | State rain scores: [3.3400e-03 3.2136e-03 6.7374e-04 2.0468e-03 8.1415e-01]

38

2026-08-09 19:07:31,906 | INFO | Fold 38 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  86%|████████▋ | 38/44 [07:38<01:36, 16.03s/fold, Train=2026-01-01→2026-07-14 | Eval=2026-07-15]2026-08-09 19:07:31,907 | INFO | Fold 39/44 | Train: 2026-01-01→2026-07-14 | Eval: 2026-07-15
2026-08-09 19:07:31,942 | INFO | Training rows: 280,778 | Evaluation rows: 1,440
2026-08-09 19:07:46,942 | WARNING | Model is not converging.  Current: 2465332.039631225 is not greater than 2465332.0400144067. Delta is -0.00038318149745464325
2026-08-09 19:07:46,951 | INFO | HMM trained | iterations=26 | converged=True
2026-08-09 19:07:47,220 | INFO | State rain scores: [3.3129e-03 3.1912e-03 6.6957e-04 2.0202e-03 8.1095e-01]

39

2026-08-09 19:07:47,457 | INFO | Fold 39 metrics | Brier=0.0136 | ROC-AUC=0.9123 | PR-AUC=0.4709 | F1=0.6598
Walk-forward HMM:  89%|████████▊ | 39/44 [07:54<01:19, 15.89s/fold, Train=2026-01-01→2026-07-19 | Eval=2026-07-20]2026-08-09 19:07:47,458 | INFO | Fold 40/44 | Train: 2026-01-01→2026-07-19 | Eval: 2026-07-20
2026-08-09 19:07:47,486 | INFO | Training rows: 287,978 | Evaluation rows: 1,440
2026-08-09 19:08:02,844 | INFO | HMM trained | iterations=26 | converged=True
2026-08-09 19:08:03,125 | INFO | State rain scores: [3.2621e-03 3.0759e-03 6.6098e-04 1.9152e-03 8.0957e-01]

40

2026-08-09 19:08:03,360 | INFO | Fold 40 metrics | Brier=0.0045 | ROC-AUC=0.9857 | PR-AUC=0.6719 | F1=0.7931
Walk-forward HMM:  91%|█████████ | 40/44 [08:10<01:03, 15.89s/fold, Train=2026-01-01→2026-07-24 | Eval=2026-07-25]2026-08-09 19:08:03,361 | INFO | Fold 41/44 | Train: 2026-01-01→2026-07-24 | Eval: 2026-07-25
2026-08-09 19:08:03,390 | INFO | Training rows: 295,178 | Evaluation rows: 1,440
2026-08-09 19:08:24,578 | INFO | HMM trained | iterations=36 | converged=True
2026-08-09 19:08:24,834 | INFO | State rain scores: [3.1171e-03 3.1074e-03 6.6028e-04 1.8519e-03 8.0928e-01]

41

2026-08-09 19:08:25,067 | INFO | Fold 41 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  93%|█████████▎| 41/44 [08:31<00:52, 17.64s/fold, Train=2026-01-01→2026-07-29 | Eval=2026-07-30]2026-08-09 19:08:25,070 | INFO | Fold 42/44 | Train: 2026-01-01→2026-07-29 | Eval: 2026-07-30
2026-08-09 19:08:25,101 | INFO | Training rows: 302,378 | Evaluation rows: 1,440
2026-08-09 19:08:44,355 | INFO | HMM trained | iterations=32 | converged=True
2026-08-09 19:08:44,625 | INFO | State rain scores: [2.9716e-03 3.0029e-03 6.6489e-04 1.8519e-03 8.0928e-01]

42

2026-08-09 19:08:44,901 | INFO | Fold 42 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  95%|█████████▌| 42/44 [08:51<00:36, 18.30s/fold, Train=2026-01-01→2026-08-03 | Eval=2026-08-04]2026-08-09 19:08:44,903 | INFO | Fold 43/44 | Train: 2026-01-01→2026-08-03 | Eval: 2026-08-04
2026-08-09 19:08:44,933 | INFO | Training rows: 309,578 | Evaluation rows: 1,440
2026-08-09 19:09:07,742 | INFO | HMM trained | iterations=37 | converged=True
2026-08-09 19:09:08,017 | INFO | State rain scores: [2.8049e-03 2.9923e-03 6.6872e-04 1.7995e-03 8.0928e-01]

43

2026-08-09 19:09:08,252 | INFO | Fold 43 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM:  98%|█████████▊| 43/44 [09:15<00:19, 19.81s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]2026-08-09 19:09:08,254 | INFO | Fold 44/44 | Train: 2026-01-01→2026-08-08 | Eval: 2026-08-09
2026-08-09 19:09:08,282 | INFO | Training rows: 316,778 | Evaluation rows: 60
2026-08-09 19:09:30,435 | WARNING | Model is not converging.  Current: 2893357.782126338 is not greater than 2893357.783068799. Delta is -0.0009424607269465923
2026-08-09 19:09:30,447 | INFO | HMM trained | iterations=35 | converged=True
2026-08-09 19:09:30,759 | INFO | State rain scores: [2.7159e-03 2.9681e-03 6.5482e-04 1.7157e-03 8.0928e-01]
2026-08-09 19:09:30,789 | INFO | Fold 44 metrics | Brier=0.0000 | ROC-AUC=0.0000 | PR-AUC=0.0000 | F1=0.0000
Walk-forward HMM: 100%|██████████| 44/44 [09:37<00:00, 20.63s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]

44

2026-08-09 19:09:32,080 | INFO | Overall metrics | Brier=0.0077 | ROC-AUC=0.9830 | PR-AUC=0.8514 | F1=0.8913
2026-08-09 19:09:32,081 | INFO | Experiment complete. Results saved to: results
Walk-forward HMM: 100%|██████████| 44/44 [09:38<00:00, 13.16s/fold, Train=2026-01-01→2026-08-08 | Eval=2026-08-09]

In [9]:
train_df

,Station,Date/Time,Temperature (°C),1-minute Precipitation (mm),Precipitation Presence (Presence/Absence),Wind Direction (deg),Wind Speed (m/s),Local Pressure (hPa),Sea-level Pressure (hPa),Humidity (%),Solar Radiation (MJ/m^2),Sunshine Duration (Sec),wind_dir_sin,wind_dir_cos,humidity_change_5min,pressure_change_5min,wind_change_5min,rain_5min,future_rain_score,_date
0,939,2026-01-01 00:01:00,-2.8,0.0,0.0,81.2,1.7,1017.5,1023.8,21.1,,,0.988228,0.152986,0.0,0.0,0.0,0.0,0.0,2026-01-01
1,939,2026-01-01 00:02:00,-2.8,0.0,0.0,88.1,2.2,1017.5,1023.8,21.1,,,0.999450,0.033155,0.0,0.0,0.0,0.0,0.0,2026-01-01
2,939,2026-01-01 00:03:00,-3.0,0.0,0.0,95.1,1.4,1017.5,1023.8,21.4,,,0.996041,-0.088894,0.0,0.0,0.0,0.0,0.0,2026-01-01
3,939,2026-01-01 00:04:00,-3.0,0.0,0.0,80.9,1.8,1017.4,1023.7,21.7,,,0.987414,0.158158,0.0,0.0,0.0,0.0,0.0,2026-01-01
4,939,2026-01-01 00:05:00,-2.9,0.0,0.0,66.4,0.9,1017.4,1023.7,21.8,,,0.916363,0.400349,0.0,0.0,0.0,0.0,0.0,2026-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316773,939,2026-08-08 23:55:00,28.1,0.0,0.0,52.3,2.7,1001.5,1007,65.7,,,0.791224,0.611527,0.1,0.0,0.4,0.0,0.0,2026-08-08
316774,939,2026-08-08 23:56:00,28.1,0.0,0.0,32.2,2.5,1001.5,1007,65.0,,,0.532876,0.846193,-0.6,0.0,0.7,0.0,0.0,2026-08-08
316775,939,2026-08-08 23:57:00,28.1,0.0,0.0,30.0,2.6,1001.5,1007,65.3,,,0.500000,0.866025,-0.4,0.0,-0.4,0.0,0.0,2026-08-08
316776,939,2026-08-08 23:58:00,28.1,0.0,0.0,50.5,4.0,1001.5,1007,64.8,,,0.771625,0.636078,-0.8,0.0,1.0,0.0,0.0,2026-08-08
316777,939,2026-08-08 23:59:00,28.1,0.0,0.0,27.9,2.1,1001.4,1006.9,64.8,,,0.467930,0.883766,-0.6,-0.2,-2.3,0.0,0.0,2026-08-08